"""
ff7nx_patchgroups.py -- GENERATED by ff7nx_resolve.py. Do not hand-edit.

Each entry is (label, module_offset, expected_stock_word, new_word).
Every offset was resolved from FFNx's own patch specs through the
x86->ARM64 recompilation map, and every stock word is verified
before it is written.

battle_frame_multiplier = 4, common_frame_multiplier = 2
Resolver self-validation against hand-derived, hardware-confirmed
patches at generation time: 5/6 reproduced.

NOTHING HERE IS HARDWARE-CONFIRMED. Every group is off by default and
must be enabled explicitly, one at a time, so a test result means
something. See HANDOFF 5g.

PATCH_GROUPS holds only functions where EVERY constant FFNx
scales is accounted for. PARTIAL_GROUPS holds the rest --
functions we can only partly scale. Partial is not "less
benefit", it is desynchronisation: three of the five
battle_sub_5B9EC2 colour constants made enemies render white.
"""

PATCH_GROUPS = {
    'battle_aura': [
        ('tifa_limit_2_1_sub_4E48D4+0x1FE',
         0x003F5ADC, 0x7100311F, 0x7100C11F),  # subs byte 12->48  [1/1]
        ('vincent_limit_fade_effect_sub_5D4240+0x24',
         0x00833708, 0x321F0FE8, 0x52800F08),  # movi WORD 30->120  [3/3]
        ('vincent_limit_fade_effect_sub_5D4240+0x57',
         0x008337C0, 0x321C03E8, 0x52800808),  # movi WORD 16->64  [3/3]
        ('vincent_limit_fade_effect_sub_5D4240+0x6E',
         0x00833800, 0x321F0BE8, 0x52800708),  # movi byte 14->56  [3/3]
    ],
    'battle_camera': [
        ('battle_sub_429AC0+0x152',
         0x000D1F90, 0x528007A8, 0x52801E88),  # movz byte 61->244  [1/1]
        ('battle_sub_429D8A+0x1D8',
         0x000D5DCC, 0x321F0FE8, 0x52800F08),  # movi byte 30->120  [1/1]
    ],
    'battle_damage': [
        ('battle_handle_player_mark_5B9C8E+0x6A',
         0x007BE21C, 0x11020108, 0x11008108),  # add WORD 128->32  [1/1]
    ],
    'battle_misc': [
        ('battle_sub_425E5F+0x3A',
         0x000C0F00, 0x320007E8, 0x52800188),  # movi WORD 3->12  [1/1]
        ('battle_sub_42A72D+0x11A',
         0x000D3994, 0x321F0BE8, 0x52800708),  # movi byte 14->56  [1/1]
        ('battle_sub_434C8B+0x4F',
         0x000F34FC, 0x32000FE8, 0x52800788),  # movi WORD 15->60  [1/1]
        ('battle_sub_435D81+0x6A8',
         0x000F6C0C, 0x528005E8, 0x52801788),  # movz WORD 47->188  [1/1]
        ('battle_sub_5BCD42+0x5B',
         0x007CB3C0, 0x32000FE8, 0x52800788),  # movi WORD 15->60  [2/2]
        ('battle_sub_5BCD42+0x6E',
         0x007CB3E8, 0x321C03E8, 0x52800088),  # movi WORD 16->4  [2/2]
        ('battle_sub_5BCF9D+0x3A',
         0x007CBA94, 0x528002A8, 0x52800A88),  # movz WORD 21->84  [1/1]
        ('battle_sub_5BD050+0x1DC',
         0x007CC35C, 0x531E7508, 0x53007D08),  # lsl byte 2->0  [2/2]
        ('battle_sub_5BD050+0x203',
         0x007CC3CC, 0x531E7508, 0x53007D08),  # lsl byte 2->0  [2/2]
        ('battle_menu_closing_window_box_6DAEF0+0x29',
         0x00D6B7AC, 0x13027D08, 0x13017D08),  # asr byte 2->1  [2/2]
        ('battle_menu_closing_window_box_6DAEF0+0x72',
         0x00D6B884, 0x13027D08, 0x13017D08),  # asr byte 2->1  [2/2]
    ],
    'battleground': [
        ('battleground_midgar_flashback_rain_5BDC4F+0x44',
         0x007CE02C, 0x7100211F, 0x7100811F),  # subs byte 8->32  [3/3]
        ('battleground_midgar_flashback_rain_5BDC4F+0x156',
         0x007CE3F0, 0x11008108, 0x11002108),  # add byte 32->8  [3/3]
        ('battleground_midgar_flashback_rain_5BDC4F+0x71',
         0x007CE4C0, 0x11064108, 0x11019108),  # add WORD 400->100  [3/3]
    ],
    'enemy_death': [
        ('battle_disintegrate_2_death_5BBA82+0x40',
         0x007C6CEC, 0x321F0BE8, 0x52800708),  # movi WORD 14->56  [1/1]
        ('battle_disintegrate_2_death_sub_5BBBDE+0xB9',
         0x007C7288, 0x11020108, 0x11008108),  # add WORD 128->32  [2/2]
        ('battle_disintegrate_2_death_sub_5BBBDE+0xDB',
         0x007C72E0, 0x51004108, 0x51001108),  # sub byte 16->4  [2/2]
        ('battle_enemy_death_5BBD24+0x40',
         0x007C771C, 0x321F0BE8, 0x52800708),  # movi WORD 14->56  [1/1]
        ('battle_enemy_death_sub_5BBE32+0xA8',
         0x007C7AB4, 0x11020108, 0x11008108),  # add WORD 128->32  [2/2]
        ('battle_enemy_death_sub_5BBE32+0xCB',
         0x007C7B0C, 0x51004108, 0x51001108),  # sub byte 16->4  [2/2]
        ('battle_melting_death_5BC21F+0x40',
         0x007C88FC, 0x321F0BE8, 0x52800708),  # movi WORD 14->56  [1/1]
        ('battle_melting_death_sub_5BC32D+0xAB',
         0x007C8C9C, 0x11020108, 0x11008108),  # add WORD 128->32  [5/5]
        ('battle_melting_death_sub_5BC32D+0xCE',
         0x007C8CF4, 0x51004108, 0x51001108),  # sub byte 16->4  [5/5]
        ('battle_melting_death_sub_5BC32D+0xEE',
         0x007C8D50, 0x11040108, 0x11010108),  # add WORD 256->64  [5/5]
        ('battle_melting_death_sub_5BC32D+0x10D',
         0x007C8DA8, 0x51040108, 0x51010108),  # sub WORD 256->64  [5/5]
        ('battle_melting_death_sub_5BC32D+0x12C',
         0x007C8E00, 0x11040108, 0x11010108),  # add WORD 256->64  [5/5]
        ('battle_morph_death_5BC812+0x40',
         0x007CA110, 0x321C03E8, 0x52800808),  # movi WORD 16->64  [1/1]
        ('battle_morph_death_sub_5BC920+0x9F',
         0x007CA4C0, 0x11020108, 0x11008108),  # add WORD 128->32  [5/5]
        ('battle_morph_death_sub_5BC920+0xC2',
         0x007CA518, 0x51002108, 0x51000908),  # sub byte 8->2  [5/5]
        ('battle_morph_death_sub_5BC920+0xE3',
         0x007CA570, 0x51002108, 0x51000908),  # sub byte 8->2  [5/5]
        ('battle_morph_death_sub_5BC920+0x104',
         0x007CA5C8, 0x51002108, 0x51000908),  # sub byte 8->2  [5/5]
        ('battle_morph_death_sub_5BC920+0x154',
         0x007CA6A0, 0x11040108, 0x11010108),  # add WORD 256->64  [5/5]
        ('battle_iainuki_death_5BCAAA+0x40',
         0x007CA990, 0x321C03E8, 0x52800808),  # movi WORD 16->64  [1/1]
        ('battle_iainuki_death_sub_5BCBB8+0x9F',
         0x007CAD40, 0x11020108, 0x11008108),  # add WORD 128->32  [5/5]
        ('battle_iainuki_death_sub_5BCBB8+0xC2',
         0x007CAD98, 0x51002108, 0x51000908),  # sub byte 8->2  [5/5]
        ('battle_iainuki_death_sub_5BCBB8+0xE3',
         0x007CADF0, 0x51002108, 0x51000908),  # sub byte 8->2  [5/5]
        ('battle_iainuki_death_sub_5BCBB8+0x104',
         0x007CAE48, 0x51002108, 0x51000908),  # sub byte 8->2  [5/5]
        ('battle_iainuki_death_sub_5BCBB8+0x154',
         0x007CAF20, 0x51020108, 0x51008108),  # sub WORD 128->32  [5/5]
    ],
    'field_fade': [
        ('field_initialize_variables+0x123',
         0x0093A9A4, 0x321C03E8, 0x52800108),  # movi short 16->8  [1/1]
        ('field_handle_screen_fading+0x210',
         0x009F6A40, 0x7100891F, 0x7100C91F),  # subs byte 34->50  [2/2]
        ('field_handle_screen_fading+0x240',
         0x009F6E10, 0x52800448, 0x52800628),  # movz int 34->49  [2/2]
    ],
    'field_models': [
        ('field_update_models_positions+0xC89',
         0x009D8720, 0x1287CFFC, 0x1281F3FC),  # movn int -16000->-4000  [4/4] covers 2 x86 sites
        ('field_update_models_positions+0x1041',
         0x009D9B30, 0x13027D08, 0x13017D08),  # asr byte 2->1  [4/4]
        ('field_update_models_positions+0x189A',
         0x009DB0CC, 0x13027D08, 0x13017D08),  # asr byte 2->1  [4/4]
    ],
    'field_text': [
        ('field_opcode_message_update_loop_630D50+0x1AC',
         0x00970974, 0x51000908, 0x51000508),  # sub short 2->1  [2/2]
        ('field_opcode_message_update_loop_630D50+0x2CF',
         0x00970BC4, 0x51000908, 0x51000508),  # sub short 2->1  [2/2]
        ('field_text_box_window_reverse_paging_632CAA+0x42',
         0x009D2914, 0x51000908, 0x51000508),  # sub short 2->1  [1/1]
        ('field_text_box_window_closing_632EB8+0x64',
         0x009D2E74, 0x13027D08, 0x13037D08),  # asr byte 2->3  [2/2]
        ('field_text_box_window_closing_632EB8+0xBF',
         0x009D2F7C, 0x13027D08, 0x13037D08),  # asr byte 2->3  [2/2]
    ],
    'summons': [
        ('run_bahamut_neo_movement_48D7BC+0x62',
         0x00271118, 0x51033D09, 0x51033909),  # sub int 207->206  [1/1]
        ('run_bahamut_movement_49ADEC+0x69',
         0x002AAAA8, 0x51015109, 0x51014D09),  # sub byte 84->83  [1/1]
        ('run_odin_gunge_movement_4A584D+0x1D0',
         0x002DAF88, 0x7100611F, 0x7100691F),  # subs byte 24->26  [1/1]
    ],
    'swirl': [
        ('swirl_main_loop+0x79',
         0x00011B94, 0x71000D1F, 0x7100191F),  # subs byte 3->6  [2/2]
        ('swirl_main_loop+0x184',
         0x00012020, 0x71000D1F, 0x7100191F),  # subs byte 3->6  [2/2]
    ],
    'world': [
        ('world_init_variables_74E1E9+0x15D',
         0x00F2B8FC, 0x321F03E8, 0x52800028),  # movi DWORD 2->1  [1/1]
        ('world_opcode_message+0x1AC',
         0x00F88034, 0x51000908, 0x51000508),  # sub short 2->1  [2/2]
        ('world_opcode_message+0x2CF',
         0x00F88270, 0x51000908, 0x51000508),  # sub short 2->1  [2/2]
        ('world_text_box_window_opening_769A66+0x3D',
         0x00FA594C, 0x13027D08, 0x13037D08),  # asr byte 2->3  [2/2]
        ('world_text_box_window_opening_769A66+0xD2',
         0x00FA5B64, 0x13027D08, 0x13037D08),  # asr byte 2->3  [2/2]
        ('world_text_box_reverse_paging_76ABE9+0x42',
         0x00FA8A54, 0x51000908, 0x51000508),  # sub short 2->1  [1/1]
        ('world_text_box_window_closing_76ADF7+0x67',
         0x00FA8FC4, 0x13027D08, 0x13037D08),  # asr byte 2->3  [2/2]
        ('world_text_box_window_closing_76ADF7+0xC2',
         0x00FA90CC, 0x13027D08, 0x13037D08),  # asr byte 2->3  [2/2]
    ],
}

PARTIAL_GROUPS = {
    'battle_aura': [
        ('limit_break_aura_effects_5C0572+0x6E',
         0x007D8244, 0x7100213F, 0x7100813F),  # subs byte 8->32  [4/7] covers 2 x86 sites
        ('limit_break_aura_effects_5C0572+0x98',
         0x007D8284, 0x7100411F, 0x7101011F),  # subs byte 16->64  [4/7]
        ('limit_break_aura_effects_5C0572+0x13E',
         0x007D853C, 0x71003D1F, 0x7100F11F),  # subs byte 15->60  [4/7]
        ('enemy_skill_aura_effects_5C06BF+0xA7',
         0x007D87D0, 0x7100213F, 0x7100813F),  # subs byte 8->32  [4/9] covers 2 x86 sites
        ('enemy_skill_aura_effects_5C06BF+0xD9',
         0x007D8808, 0x53144D08, 0x53165508),  # lsl byte 12->10  [4/9]
        ('enemy_skill_aura_effects_5C06BF+0x182',
         0x007D8AA8, 0x71003D1F, 0x7100F11F),  # subs byte 15->60  [4/9]
        ('summon_aura_effects_5C0953+0x19D',
         0x007D9704, 0x7100211F, 0x7100811F),  # subs byte 8->32  [1/2]
    ],
    'battle_camera': [
        ('battle_sub_430DD0+0x326',
         0x0009D668, 0x321F0FE8, 0x52800F08),  # movi DWORD 30->120  [2/4]
        ('battle_sub_430DD0+0x3DE',
         0x0009E510, 0x52800628, 0x52801888),  # movz DWORD 49->196  [2/4]
    ],
    'battle_escape': [
        ('battle_escape_magic_init_data_5D59B0+0x1E8',
         0x0083A130, 0x321903FC, 0x5280041C),  # movi DWORD 128->32  [7/8]
        ('battle_escape_magic_init_data_5D59B0+0x12C',
         0x0083A728, 0x12002508, 0x12001D08),  # and DWORD 1023->255  [7/8]
        ('battle_escape_magic_init_data_5D59B0+0x131',
         0x0083A72C, 0x51080108, 0x51020108),  # sub DWORD 512->128  [7/8]
        ('battle_escape_magic_init_data_5D59B0+0x148',
         0x0083A774, 0x12002508, 0x12001D08),  # and DWORD 1023->255  [7/8]
        ('battle_escape_magic_init_data_5D59B0+0x14D',
         0x0083A778, 0x51080108, 0x51020108),  # sub DWORD 512->128  [7/8]
        ('battle_escape_magic_init_data_5D59B0+0x164',
         0x0083A7C0, 0x12002508, 0x12001D08),  # and DWORD 1023->255  [7/8]
        ('battle_escape_magic_init_data_5D59B0+0x169',
         0x0083A7C4, 0x51080108, 0x51020108),  # sub DWORD 512->128  [7/8]
        ('battle_escape_magic_loop_5D602A+0x3B',
         0x0083BD54, 0x51007909, 0x5101E109),  # sub byte 30->120  [6/9]
        ('battle_escape_magic_loop_5D602A+0x2FB',
         0x0083BD88, 0x51007914, 0x5101E114),  # sub byte 30->120  [6/9]
        ('battle_escape_magic_loop_5D602A+0x302',
         0x0083BDBC, 0x51007909, 0x5101E109),  # sub byte 30->120  [6/9]
        ('battle_escape_magic_loop_5D602A+0x8F0',
         0x0083BDF0, 0x51007913, 0x5101E113),  # sub byte 30->120  [6/9]
        ('battle_escape_magic_loop_5D602A+0xC1',
         0x0083BFA0, 0x52803E9C, 0x52800FBC),  # movz DWORD 500->125  [6/9]
        ('battle_escape_magic_loop_5D602A+0x6A8',
         0x0083D7C8, 0x13047D08, 0x13067D08),  # asr byte 4->6  [6/9]
    ],
    'battle_misc': [
        ('battle_sub_5B9EC2+0x1CB',
         0x007BEF04, 0x11040108, 0x11010108),  # add WORD 256->64  [3/5]
        ('battle_sub_5B9EC2+0x292',
         0x007BF108, 0x7100413F, 0x7101013F),  # subs byte 16->64  [3/5]
        ('battle_sub_5B9EC2+0x316',
         0x007BF1F4, 0x12001108, 0x12001908),  # and byte 31->127  [3/5]
        ('field_init_viewport_values+0x6E',
         0x00929964, 0x321B0BE8, 0x52801E08),  # movi int 224->240  [1/2]
        ('display_tifa_slots_handler_6E3135+0x168',
         0x00D49F78, 0x12000908, 0x12000508),  # and byte 7->3  [1/2]
    ],
    'battleground': [
        ('update_3d_battleground+0x1D4',
         0x000E0820, 0x52807D13, 0x52801F53),  # movz int 1000->250  [11/13] covers 8 x86 sites
        ('update_3d_battleground+0x617',
         0x000E1488, 0x51019118, 0x51006518),  # sub WORD 100->25  [11/13]
        ('update_3d_battleground+0x6CE',
         0x000E1778, 0x5101911A, 0x5100651A),  # sub WORD 100->25  [11/13]
        ('update_3d_battleground+0x8C7',
         0x000E1F54, 0x11001918, 0x11000518),  # add byte 6->1  [11/13]
        ('battleground_vertical_scrolling_42F126+0x10',
         0x000E6030, 0x7100413F, 0x7101013F),  # subs byte 16->64  [1/4]
    ],
    'field_text': [
        ('field_text_box_window_paging_631945+0xFD',
         0x009CF7EC, 0x13057D08, 0x13067D08),  # asr byte 5->6  [2/4]
        ('field_text_box_window_paging_631945+0x141',
         0x009CF8C8, 0x13047D08, 0x13057D08),  # asr byte 4->5  [2/4]
    ],
    'summons': [
        ('run_shiva_movement_592538+0x153',
         0x00700534, 0x7101651F, 0x71016D1F),  # subs byte 89->91  [1/2]
    ],
    'swirl': [
        ('swirl_loop_sub_4026D4+0x3E',
         0x000130B4, 0x7100B928, 0x7100C928),  # subs byte 46->50  [2/3]
        ('swirl_loop_sub_4026D4+0x111',
         0x000133B8, 0x71013928, 0x7101FD28),  # subs byte 78->127  [2/3]
    ],
    'world': [
        ('world_text_box_window_paging_769C02+0x10A',
         0x00FA61BC, 0x321F03E8, 0x52800028),  # movi WORD 2->1  [3/4]
        ('world_text_box_window_paging_769C02+0xF6',
         0x00FA61E4, 0x13057D08, 0x13067D08),  # asr byte 5->6  [3/4]
        ('world_text_box_window_paging_769C02+0x13A',
         0x00FA629C, 0x13047D08, 0x13057D08),  # asr byte 4->5  [3/4]
    ],
}

CODE_PAIRED_GROUPS = {
    'battle_damage': [
        ('display_battle_damage_5BB410+0x54',
         0x007C5400, 0x52800168, 0x52800588),  # movz WORD 11->44  [1/5]
    ],
    'enemy_death': [
        ('battle_disintegrate_1_death_5BBF31+0x40',
         0x007C7E40, 0x321F0BE8, 0x52800708),  # movi WORD 14->56  [1/1]
        ('battle_boss_death_5BC48C+0x40',
         0x007C9130, 0x321A03F6, 0x52802016),  # movi WORD 64->256  [2/2] covers 2 x86 sites
        ('battle_boss_death_sub_5BC6ED+0xCF',
         0x007C9AAC, 0x11008108, 0x11002108),  # add byte 32->8  [1/2]
    ],
    'field_text': [
        ('field_text_box_window_opening_6317A9+0x3D',
         0x009CEF4C, 0x13027D08, 0x13037D08),  # asr byte 2->3  [2/2]
        ('field_text_box_window_opening_6317A9+0xD2',
         0x009CF164, 0x13027D08, 0x13037D08),  # asr byte 2->3  [2/2]
    ],
    'summons': [
        ('run_odin_steel_sub_4A9908+0x5E',
         0x002EBF40, 0x32000FF6, 0x52800796),  # movi DWORD 15->60  [3/4] covers 2 x86 sites
        ('run_odin_steel_sub_4A9908+0x265',
         0x002EBFAC, 0x71000D1F, 0x7100311F),  # subs byte 3->12  [3/4]
    ],
}

# post-call return-value scalers: FFNx wraps the call to
# get_bank_value inside these opcode handlers and scales the
# result. hook is the instruction AFTER the translated bl; ctx
# is the guest CPU context register for that function.
OPCODE_SITES = [
    dict(name='JUMP', op='mul', hook=0x00965ACC, displaced=0xB94012A8,
         ctx=21, handler=0x615CA3, x86_call=0x615E94, what='field jump arc: lands before the animation ends'),
    dict(name='SCRLA', op='mul', hook=0x0097A190, displaced=0xB94012C8,
         ctx=22, handler=0x61A607, x86_call=0x61A679, what='scripted scroll / elevator speed'),
    dict(name='SCR2DC', op='mul', hook=0x0097A8C4, displaced=0xB9401288,
         ctx=20, handler=0x61A7F9, x86_call=0x61A835, what='scripted 2D scroll with constant speed'),
    dict(name='SCR2DL', op='mul', hook=0x0097AB20, displaced=0xB9401288,
         ctx=20, handler=0x61A878, x86_call=0x61A8B4, what='scripted 2D scroll, linear'),
    dict(name='SCRLP', op='mul', hook=0x0097A500, displaced=0xB94012C8,
         ctx=22, handler=0x61A6BD, x86_call=0x61A764, what='scripted scroll to party'),
    dict(name='OFST', op='mul', hook=0x0096A66C, displaced=0xB94012A8,
         ctx=21, handler=0x6172E8, x86_call=0x61732E, what='model offset movement'),
    dict(name='VWOFT', op='mul', hook=0x009840B4, displaced=0xB94012C8,
         ctx=22, handler=0x61CA5C, x86_call=0x61CB28, what='view offset'),
    dict(name='NFADE', op='div', hook=0x00988FDC, displaced=0xB94012A8,
         ctx=21, handler=0x61E099, x86_call=0x61E122, what='screen fade frame count'),
]

# symbol -> (constants we can apply, constants FFNx scales)
COVERAGE = {
    'aerith_limit_2_1_sub_45B0CF': (0, 1),
    'battle_boss_death_5BC48C': (2, 2),
    'battle_boss_death_sub_5BC6ED': (1, 2),
    'battle_disintegrate_1_death_5BBF31': (1, 1),
    'battle_disintegrate_2_death_5BBA82': (1, 1),
    'battle_disintegrate_2_death_sub_5BBBDE': (2, 2),
    'battle_enemy_death_5BBD24': (1, 1),
    'battle_enemy_death_sub_5BBE32': (2, 2),
    'battle_escape_magic_init_data_5D59B0': (7, 8),
    'battle_escape_magic_loop_5D602A': (6, 9),
    'battle_fps_menu_multiplier': (0, 1),
    'battle_handle_player_mark_5B9C8E': (1, 1),
    'battle_handle_status_effect_anim_5BA7C0': (0, 1),
    'battle_iainuki_death_5BCAAA': (1, 1),
    'battle_iainuki_death_sub_5BCBB8': (5, 5),
    'battle_melting_death_5BC21F': (1, 1),
    'battle_melting_death_sub_5BC32D': (5, 5),
    'battle_menu_closing_window_box_6DAEF0': (2, 2),
    'battle_morph_death_5BC812': (1, 1),
    'battle_morph_death_sub_5BC920': (5, 5),
    'battle_sub_425E5F': (1, 1),
    'battle_sub_429AC0': (1, 1),
    'battle_sub_429D8A': (1, 1),
    'battle_sub_42A72D': (1, 1),
    'battle_sub_430DD0': (2, 4),
    'battle_sub_434C8B': (1, 1),
    'battle_sub_435D81': (1, 1),
    'battle_sub_5B9EC2': (3, 5),
    'battle_sub_5BCD42': (2, 2),
    'battle_sub_5BCF9D': (1, 1),
    'battle_sub_5BD050': (2, 2),
    'battle_sub_5C18BC': (0, 2),
    'battle_sub_5C1C8F': (0, 2),
    'battleground_midgar_flashback_rain_5BDC4F': (3, 3),
    'battleground_vertical_scrolling_42F126': (1, 4),
    'coaster_sub_5EE150': (0, 4),
    'display_battle_damage_5BB410': (1, 5),
    'display_tifa_slots_handler_6E3135': (1, 2),
    'enemy_skill_aura_effects_5C06BF': (4, 9),
    'field_draw_everything': (0, 2),
    'field_float_battle_7B7680': (1, 1),
    'field_handle_screen_fading': (2, 2),
    'field_init_viewport_values': (1, 2),
    'field_initialize_variables': (1, 1),
    'field_opcode_ask_update_loop_6310A1': (0, 2),
    'field_opcode_message_update_loop_630D50': (2, 2),
    'field_text_box_window_closing_632EB8': (2, 2),
    'field_text_box_window_opening_6317A9': (2, 2),
    'field_text_box_window_paging_631945': (2, 4),
    'field_text_box_window_reverse_paging_632CAA': (1, 1),
    'field_update_models_positions': (4, 4),
    'highway_exit_address_location': (0, 1),
    'kernel_load_kernel2': (0, 1),
    'limit_break_aura_effects_5C0572': (4, 7),
    'run_bahamut_movement_49ADEC': (1, 1),
    'run_bahamut_neo_movement_48D7BC': (1, 1),
    'run_odin_gunge_movement_4A584D': (1, 1),
    'run_odin_steel_sub_4A9908': (3, 4),
    'run_ramuh_camera_597206': (0, 1),
    'run_shiva_movement_592538': (1, 2),
    'run_summon_animations_5C0E4B': (0, 3),
    'summon_aura_effects_5C0953': (1, 2),
    'swirl_loop_sub_4026D4': (2, 3),
    'swirl_main_loop': (2, 2),
    'tifa_limit_2_1_sub_4E48D4': (1, 1),
    'update_3d_battleground': (11, 13),
    'vincent_limit_fade_effect_sub_5D4240': (3, 3),
    'world_init_load_map_meshes_graphics_objects_75A283': (0, 3),
    'world_init_variables_74E1E9': (1, 1),
    'world_opcode_ask': (0, 2),
    'world_opcode_message': (2, 2),
    'world_sub_75C283': (0, 4),
    'world_submit_draw_clouds_and_meteor_7547A6': (0, 2),
    'world_text_box_reverse_paging_76ABE9': (1, 1),
    'world_text_box_window_closing_76ADF7': (2, 2),
    'world_text_box_window_opening_769A66': (2, 2),
    'world_text_box_window_paging_769C02': (3, 4),
    'world_wm0_overworld_draw_all_74C179': (0, 1),
    'world_wm2_underwater_draw_all_74C3F0': (0, 1),
    'world_wm3_snowstorm_draw_all_74C589': (0, 1),
}

# provenance: why each hook is believed correct
EVIDENCE = {
    0x003F5ADC: '1:1 narrow tier (1 x86 cmp sites, 1 ARM64 sites, position 0)',
    0x00833708: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x008337C0: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x00833800: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x000D1F90: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x000D5DCC: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x007BE21C: '1:1 narrow tier (1 x86 add sites, 1 ARM64 sites, position 0)',
    0x000C0F00: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x000D3994: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x000F34FC: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x000F6C0C: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x007CB3C0: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x007CB3E8: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x007CBA94: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x007CC35C: '1:1 narrow tier (2 x86 shl sites, 2 ARM64 sites, position 0)',
    0x007CC3CC: '1:1 narrow tier (2 x86 shl sites, 2 ARM64 sites, position 1)',
    0x00D6B7AC: '1:1 narrow tier (2 x86 sar sites, 2 ARM64 sites, position 0)',
    0x00D6B884: '1:1 narrow tier (2 x86 sar sites, 2 ARM64 sites, position 1)',
    0x007CE02C: '1:1 narrow tier (1 x86 cmp sites, 1 ARM64 sites, position 0)',
    0x007CE3F0: '1:1 narrow tier (1 x86 add sites, 1 ARM64 sites, position 0)',
    0x007CE4C0: '1:1 narrow tier (1 x86 add sites, 1 ARM64 sites, position 0)',
    0x007C6CEC: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x007C7288: '1:1 narrow tier (1 x86 add sites, 1 ARM64 sites, position 0)',
    0x007C72E0: '1:1 narrow tier (1 x86 sub sites, 1 ARM64 sites, position 0)',
    0x007C771C: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x007C7AB4: '1:1 narrow tier (1 x86 add sites, 1 ARM64 sites, position 0)',
    0x007C7B0C: '1:1 narrow tier (1 x86 sub sites, 1 ARM64 sites, position 0)',
    0x007C88FC: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x007C8C9C: '1:1 narrow tier (1 x86 add sites, 1 ARM64 sites, position 0)',
    0x007C8CF4: '1:1 narrow tier (1 x86 sub sites, 1 ARM64 sites, position 0)',
    0x007C8D50: '1:1 narrow tier (2 x86 add sites, 2 ARM64 sites, position 0)',
    0x007C8DA8: '1:1 narrow tier (1 x86 sub sites, 1 ARM64 sites, position 0)',
    0x007C8E00: '1:1 narrow tier (2 x86 add sites, 2 ARM64 sites, position 1)',
    0x007CA110: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x007CA4C0: '1:1 narrow tier (1 x86 add sites, 1 ARM64 sites, position 0)',
    0x007CA518: '1:1 narrow tier (3 x86 sub sites, 3 ARM64 sites, position 0)',
    0x007CA570: '1:1 narrow tier (3 x86 sub sites, 3 ARM64 sites, position 1)',
    0x007CA5C8: '1:1 narrow tier (3 x86 sub sites, 3 ARM64 sites, position 2)',
    0x007CA6A0: '1:1 narrow tier (1 x86 add sites, 1 ARM64 sites, position 0)',
    0x007CA990: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x007CAD40: '1:1 narrow tier (1 x86 add sites, 1 ARM64 sites, position 0)',
    0x007CAD98: '1:1 narrow tier (3 x86 sub sites, 3 ARM64 sites, position 0)',
    0x007CADF0: '1:1 narrow tier (3 x86 sub sites, 3 ARM64 sites, position 1)',
    0x007CAE48: '1:1 narrow tier (3 x86 sub sites, 3 ARM64 sites, position 2)',
    0x007CAF20: '1:1 narrow tier (1 x86 sub sites, 1 ARM64 sites, position 0)',
    0x0093A9A4: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x009F6A40: '1:1 narrow tier (1 x86 cmp sites, 1 ARM64 sites, position 0)',
    0x009F6E10: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x009D8720: 'hoisted constant shared by all 2 x86 sites, and FFNx patches all 2',
    0x009D9B30: '1:1 narrow tier (2 x86 sar sites, 2 ARM64 sites, position 0)',
    0x009DB0CC: '1:1 narrow tier (2 x86 sar sites, 2 ARM64 sites, position 1)',
    0x00970974: '1:1 narrow tier (2 x86 sub sites, 2 ARM64 sites, position 0)',
    0x00970BC4: '1:1 narrow tier (2 x86 sub sites, 2 ARM64 sites, position 1)',
    0x009D2914: '1:1 narrow tier (1 x86 sub sites, 1 ARM64 sites, position 0)',
    0x009D2E74: '1:1 narrow tier (2 x86 sar sites, 2 ARM64 sites, position 0)',
    0x009D2F7C: '1:1 narrow tier (2 x86 sar sites, 2 ARM64 sites, position 1)',
    0x00271118: '1:1 narrow tier (2 x86 cmp/sub sites, 2 ARM64 sites, position 0)',
    0x002AAAA8: '1:1 narrow tier (2 x86 cmp/sub sites, 2 ARM64 sites, position 0)',
    0x002DAF88: '1:1 narrow tier (1 x86 cmp sites, 1 ARM64 sites, position 0)',
    0x00011B94: '1:1 narrow tier (2 x86 cmp sites, 2 ARM64 sites, position 0)',
    0x00012020: '1:1 narrow tier (2 x86 cmp sites, 2 ARM64 sites, position 1)',
    0x00F2B8FC: '1:1 narrow tier (1 x86 mov sites, 1 ARM64 sites, position 0)',
    0x00F88034: '1:1 narrow tier (2 x86 sub sites, 2 ARM64 sites, position 0)',
    0x00F88270: '1:1 narrow tier (2 x86 sub sites, 2 ARM64 sites, position 1)',
    0x00FA594C: '1:1 narrow tier (2 x86 sar sites, 2 ARM64 sites, position 0)',
    0x00FA5B64: '1:1 narrow tier (2 x86 sar sites, 2 ARM64 sites, position 1)',
    0x00FA8A54: '1:1 narrow tier (1 x86 sub sites, 1 ARM64 sites, position 0)',
    0x00FA8FC4: '1:1 narrow tier (2 x86 sar sites, 2 ARM64 sites, position 0)',
    0x00FA90CC: '1:1 narrow tier (2 x86 sar sites, 2 ARM64 sites, position 1)',
}

INTENT = {
    0x003F5ADC: ('subs', 12, 48),
    0x00833708: ('movi', 30, 120),
    0x008337C0: ('movi', 16, 64),
    0x00833800: ('movi', 14, 56),
    0x000D1F90: ('movz', 61, 244),
    0x000D5DCC: ('movi', 30, 120),
    0x007BE21C: ('add', 128, 32),
    0x000C0F00: ('movi', 3, 12),
    0x000D3994: ('movi', 14, 56),
    0x000F34FC: ('movi', 15, 60),
    0x000F6C0C: ('movz', 47, 188),
    0x007CB3C0: ('movi', 15, 60),
    0x007CB3E8: ('movi', 16, 4),
    0x007CBA94: ('movz', 21, 84),
    0x007CC35C: ('lsl', 2, 0),
    0x007CC3CC: ('lsl', 2, 0),
    0x00D6B7AC: ('asr', 2, 1),
    0x00D6B884: ('asr', 2, 1),
    0x007CE02C: ('subs', 8, 32),
    0x007CE3F0: ('add', 32, 8),
    0x007CE4C0: ('add', 400, 100),
    0x007C6CEC: ('movi', 14, 56),
    0x007C7288: ('add', 128, 32),
    0x007C72E0: ('sub', 16, 4),
    0x007C771C: ('movi', 14, 56),
    0x007C7AB4: ('add', 128, 32),
    0x007C7B0C: ('sub', 16, 4),
    0x007C88FC: ('movi', 14, 56),
    0x007C8C9C: ('add', 128, 32),
    0x007C8CF4: ('sub', 16, 4),
    0x007C8D50: ('add', 256, 64),
    0x007C8DA8: ('sub', 256, 64),
    0x007C8E00: ('add', 256, 64),
    0x007CA110: ('movi', 16, 64),
    0x007CA4C0: ('add', 128, 32),
    0x007CA518: ('sub', 8, 2),
    0x007CA570: ('sub', 8, 2),
    0x007CA5C8: ('sub', 8, 2),
    0x007CA6A0: ('add', 256, 64),
    0x007CA990: ('movi', 16, 64),
    0x007CAD40: ('add', 128, 32),
    0x007CAD98: ('sub', 8, 2),
    0x007CADF0: ('sub', 8, 2),
    0x007CAE48: ('sub', 8, 2),
    0x007CAF20: ('sub', 128, 32),
    0x0093A9A4: ('movi', 16, 8),
    0x009F6A40: ('subs', 34, 50),
    0x009F6E10: ('movz', 34, 49),
    0x009D8720: ('movn', -16000, -4000),
    0x009D9B30: ('asr', 2, 1),
    0x009DB0CC: ('asr', 2, 1),
    0x00970974: ('sub', 2, 1),
    0x00970BC4: ('sub', 2, 1),
    0x009D2914: ('sub', 2, 1),
    0x009D2E74: ('asr', 2, 3),
    0x009D2F7C: ('asr', 2, 3),
    0x00271118: ('sub', 207, 206),
    0x002AAAA8: ('sub', 84, 83),
    0x002DAF88: ('subs', 24, 26),
    0x00011B94: ('subs', 3, 6),
    0x00012020: ('subs', 3, 6),
    0x00F2B8FC: ('movi', 2, 1),
    0x00F88034: ('sub', 2, 1),
    0x00F88270: ('sub', 2, 1),
    0x00FA594C: ('asr', 2, 3),
    0x00FA5B64: ('asr', 2, 3),
    0x00FA8A54: ('sub', 2, 1),
    0x00FA8FC4: ('asr', 2, 3),
    0x00FA90CC: ('asr', 2, 3),
}
