# GENERATED by ff7nx_locate.py -- do not edit.
# exe ff7_en  nso exefs/main
#
# Battle effect / camera dispatcher hook sites. Every
# address here was derived through FFNx's chain and located
# by exact instruction signature; see ff7nx_dispatch.py.

FLAG_BASE = 0x3FEC328
BSS_GROW  = 0xA0
BSS_PAGE_END = 0x12CF000

# The pause-throttle scratch sits AFTER the flag blocks, so
# FLAG_BASE and BSS_GROW keep the values a build without any
# throttle group used, and that build still reproduces its old
# md5 exactly. BSS_GROW_THROTTLE is what bssSize grows by when
# any throttle group is enabled.
THROTTLE_BASE = 0x3FEC3C8
BSS_GROW_THROTTLE = 0x180
PAUSED_GUEST = 0xDC0E6C


DISPATCH_SITES = {
  'effect10': {
    'what'      : 'character movement and resting positions -- limit-break hit timing, attacker->target movement',
    'slots'     : 0xA,
    'stride'    : 0x20,
    'mask_bits' : 0x4,
    'flag'      : 0x3FEC328,
    'unhandled' : 0x0,
    'data_base' : 0xBF2E70,
    'array_fn'  : 0xBE10C0,
    'disp_x86'  : 0x5BF107,
    'disp_arm'  : 0x7D3220,
    'add_x86'   : 0x5BECF1,
    'add_arm'   : 0x7D2420,
    'throttle'  : None,
    'disp_hook' : {
        'add_pc'   : 0x7D32CC,
        'ctx_reg'  : 0x15,
        'displaced': 0x7100011F,
        'fn_reg'   : 0x8,
        'hook'     : 0x7D32DC,
        'idx_off'  : 0x8,
        'n_slots'  : 0xA,
        'sig'      : [(-16, 0x0B080B00), (-12, 0xB9000AA8), (-8, 0x9424A433), (-4, 0xB9400008), (0, 0x7100011F), (12, 0x34000728)],
    },
    'add_hook'  : {
        'add_pc'   : 0x7D26AC,
        'ctx_reg'  : 0x14,
        'displaced': 0xB9000016,
        'fn_val_reg': 0x16,
        'hook'     : 0x7D26B8,
        'idx_off'  : 0x8,
        'sig'      : [(-20, 0xB9400A88), (-12, 0x0B080AA0), (-4, 0x9424A73B), (0, 0xB9000016)],
    },
    'fields'    : {
        'field_14'  : (0x14, 32, 's'),
        'field_18'  : (0x18, 8, 'u'),
        'field_19'  : (0x19, 8, 'u'),
        'field_1A'  : (0x1A, 8, 'u'),
        'field_2'   : (0x02, 16, 's'),
        'field_6'   : (0x06, 16, 's'),
        'field_A'   : (0x0A, 16, 's'),
        'field_C'   : (0x0C, 16, 's'),
        'field_E'   : (0x0E, 16, 's'),
        'n_frames'  : (0x04, 16, 's'),
    },
    'cases'     : [
        ('battle_sub_426DE3', 0x426DE3, [('n_frames', 'mul'), ('field_18', 'mul'), ('field_C', 'div'), ('field_E', 'div'), ('field_6', 'div')], None),
        ('battle_sub_426941', 0x426941, [('n_frames', 'mul'), ('field_A', 'div'), ('field_C', 'div')], 'n_frames>1'),
        ('battle_sub_426899', 0x426899, [('n_frames', 'mul'), ('field_E', 'div')], None),
        ('battle_sub_4267F1', 0x4267F1, [('n_frames', 'mul'), ('field_A', 'div')], None),
        ('battle_move_character_sub_426A26', 0x426A26, [('n_frames', 'mul'), ('field_18', 'mul'), ('field_C', 'div'), ('field_E', 'div')], None),
        ('battle_move_character_sub_42739D', 0x42739D, [('n_frames', 'mul'), ('field_19', 'mul'), ('field_1A', 'mul'), ('field_C', 'div'), ('field_E', 'div')], None),
        ('battle_move_character_sub_426F58', 0x426F58, [('n_frames', 'mul')], None),
        ('battle_move_character_sub_4270DE', 0x4270DE, [('n_frames', 'mul'), ('field_19', 'mul'), ('field_1A', 'mul'), ('field_C', 'div'), ('field_E', 'div'), ('field_14', 'div')], None),
    ],
  },
  'effect100': {
    'what'      : 'action / damage text hold duration',
    'slots'     : 0x64,
    'stride'    : 0x20,
    'mask_bits' : 0x7,
    'flag'      : 0x3FEC338,
    'unhandled' : 0x7,
    'data_base' : 0xBFB718,
    'array_fn'  : 0xBF2858,
    'disp_x86'  : 0x5BF01F,
    'disp_arm'  : 0x7D2F30,
    'add_x86'   : 0x5BEC50,
    'add_arm'   : 0x783010,
    'throttle'  : {
        'pre'           : 0x7D3050,
        'pre_displaced' : 0xB90012C8,
        'post'          : 0x7D3058,
        'post_displaced': 0x2A1303E0,
        'call_pc'       : 0x7D3054,
        'translate_pc'  : 0x7D3040,
        'thunk'         : 0xA1A0,
        'ctx_reg'       : 0x16,
        'store_reg'     : 0x8,
        'ctr'           : 0x3FEC3C8,
        'pptr'          : 0x3FEC448,
        'saved'         : 0x3FEC450,
        'did'           : 0x3FEC451,
        'mask_bits'     : 0x7,
        'size'          : 0x90,
        'one_call_throttled': True,
        'pre_sig'       : [(-16, 0x9424A4D8), (-12, 0xB94012C8), (-8, 0xB9400000), (-4, 0x51001108), (0, 0xB90012C8), (4, 0x97E0DC53), (8, 0x2A1303E0)],
        'post_sig'      : [(-24, 0x9424A4D8), (-20, 0xB94012C8), (-16, 0xB9400000), (-12, 0x51001108), (-8, 0xB90012C8), (-4, 0x97E0DC53), (0, 0x2A1303E0)],
        'undecorated'   : [0x7D3170],
        'undecorated_words': [0x97E0DC0C],
        'exclude'       : [
            ('display_battle_action_text_42782A', 0x42782A),
            ('battle_sub_425D29', 0x425D29),
            ('battle_sub_5BDA0F', 0x5BDA0F),
            ('tifa_limit_1_2_sub_4E3D51', 0x4E3D51),
            ('tifa_limit_2_1_sub_4E48D4', 0x4E48D4),
            ('run_odin_steel_sub_4A9908', 0x4A9908),
            ('battle_enemy_death_5BBD24', 0x5BBD24),
            ('battle_iainuki_death_5BCAAA', 0x5BCAAA),
            ('battle_boss_death_5BC48C', 0x5BC48C),
            ('battle_melting_death_5BC21F', 0x5BC21F),
            ('battle_disintegrate_2_death_5BBA82', 0x5BBA82),
            ('battle_morph_death_5BC812', 0x5BC812),
            ('run_summon_animations_5C0E4B', 0x5C0E4B),
            ('run_summon_animations_script_5C1B81', 0x5C1B81),
            ('goblin_punch_flash_573291', 0x573291),
            ('run_ifrit_movement_596702', 0x596702),
            ('vincent_limit_fade_effect_sub_5D4240', 0x5D4240),
            ('cloud_limit_2_2_sub_467256', 0x467256),
            ('battle_escape_magic_loop_5D602A', 0x5D602A),
        ],
        'candidates'    : [
            ('run_chocomog_camera_509B10', 0x509B10),
            ('run_fat_chocobo_camera_507CA4', 0x507CA4),
            ('run_ifrit_camera_592A36', 0x592A36),
            ('run_shiva_camera_58E60D', 0x58E60D),
            ('run_ramuh_camera_597206', 0x597206),
            ('run_alexander_camera_501637', 0x501637),
            ('run_bahamut_camera_497A37', 0x497A37),
            ('run_phoenix_camera_515238', 0x515238),
            ('run_titan_camera_59B4B0', 0x59B4B0),
            ('run_hades_camera_4B65A8', 0x4B65A8),
            ('run_leviathan_camera_5B0716', 0x5B0716),
            ('run_odin_gunge_camera_4A0F52', 0x4A0F52),
            ('run_odin_steel_camera_4A5D3C', 0x4A5D3C),
            ('run_bahamut_neo_camera_48C75D', 0x48C75D),
            ('run_kujata_camera_4F9A4D', 0x4F9A4D),
            ('run_typhoon_camera_4D594C', 0x4D594C),
            ('run_bahamut_zero_camera_483866', 0x483866),
            ('run_kotr_camera_476AFB', 0x476AFB),
            ('barret_limit_4_1_camera_4688A2', 0x4688A2),
            ('aerith_limit_4_1_camera_473CC2', 0x473CC2),
            ('enemy_atk_camera_sub_439EE0', 0x439EE0),
            ('enemy_atk_camera_sub_44A7D2', 0x44A7D2),
            ('enemy_atk_camera_sub_44EDC0', 0x44EDC0),
            ('enemy_atk_camera_sub_4522AD', 0x4522AD),
            ('enemy_atk_camera_sub_457C60', 0x457C60),
            ('run_fat_chocobo_movement_509692', 0x509692),
            ('run_bahamut_movement_49ADEC', 0x49ADEC),
            ('run_bahamut_neo_movement_48D7BC', 0x48D7BC),
            ('run_odin_gunge_movement_4A584D', 0x4A584D),
            ('run_odin_steel_movement_4A6CB8', 0x4A6CB8),
            ('run_phoenix_movement_518AFF', 0x518AFF),
            ('run_chocomog_movement_50B1A3', 0x50B1A3),
            ('run_bahamut_zero_movement_48BBFC', 0x48BBFC),
            ('run_shiva_movement_592538', 0x592538),
            ('run_alexander_movement_5078D8', 0x5078D8),
            ('run_chocobuckle_main_loop_560C32', 0x560C32),
            ('barret_limit_4_1_model_movement_4698EF', 0x4698EF),
            ('run_bahamut_zero_main_loop_484A16', 0x484A16),
            ('death_sentence_main_loop_5661A0', 0x5661A0),
            ('roulette_skill_main_loop_566287', 0x566287),
            ('bomb_blast_black_bg_effect_537427', 0x537427),
            ('run_confu_main_loop_5600BE', 0x5600BE),
            ('death_kill_sub_loop_5624A5', 0x5624A5),
            ('death_kill_sub_loop_562C60', 0x562C60),
        ],
        'aura_allow'    : [
        ],
    },
    'disp_hook' : {
        'add_pc'   : 0x7D2FEC,
        'ctx_reg'  : 0x16,
        'displaced': 0x7100011F,
        'fn_reg'   : 0x8,
        'hook'     : 0x7D2FFC,
        'idx_off'  : 0x8,
        'n_slots'  : 0x64,
        'sig'      : [(-20, 0xB9000AC8), (-16, 0x0B080A68), (-12, 0x11128100), (-8, 0x9424A4EB), (-4, 0xB9400008), (0, 0x7100011F), (12, 0x34000868)],
    },
    'add_hook'  : {
        'add_pc'   : 0x78328C,
        'ctx_reg'  : 0x14,
        'displaced': 0xB9000015,
        'fn_val_reg': 0x15,
        'hook'     : 0x78329C,
        'idx_off'  : 0x8,
        'sig'      : [(-24, 0xB9400A88), (-16, 0x0B080A68), (-12, 0x11128100), (-4, 0x9425E442), (0, 0xB9000015)],
    },
    'fields'    : {
        'field_14'  : (0x14, 32, 's'),
        'field_18'  : (0x18, 8, 'u'),
        'field_19'  : (0x19, 8, 'u'),
        'field_1A'  : (0x1A, 16, 's'),
        'field_2'   : (0x02, 16, 's'),
        'field_6'   : (0x06, 16, 's'),
        'field_A'   : (0x0A, 16, 's'),
        'field_C'   : (0x0C, 16, 's'),
        'field_E'   : (0x0E, 16, 's'),
        'n_frames'  : (0x04, 16, 's'),
    },
    'cases'     : [
        ('display_battle_action_text_42782A', 0x42782A, [('field_6', 'mul')], None),
        ('battle_sub_425D29', 0x425D29, [('n_frames', 'mul')], None),
        ('battle_sub_5BDA0F', 0x5BDA0F, [('field_2', 'div'), ('n_frames', 'mul')], None),
        ('tifa_limit_1_2_sub_4E3D51', 0x4E3D51, [('field_1A', 'mul')], None),
        ('tifa_limit_2_1_sub_4E48D4', 0x4E48D4, [('field_1A', 'mul')], None),
    ],
  },
  'camera': {
    'what'      : 'battle camera move durations -- magic, limit break, battle intro, victory',
    'slots'     : 0x10,
    'stride'    : 0x28,
    'mask_bits' : 0x4,
    'flag'      : 0x3FEC3B8,
    'unhandled' : 0x0,
    'data_base' : 0xBFCE08,
    'array_fn'  : 0xBF2378,
    'disp_x86'  : 0x5BF27D,
    'disp_arm'  : 0x7D36C0,
    'add_x86'   : 0x5BEE33,
    'add_arm'   : 0x7D2740,
    'throttle'  : None,
    'disp_hook' : {
        'add_pc'   : 0x7D3764,
        'ctx_reg'  : 0x15,
        'displaced': 0x7100011F,
        'fn_reg'   : 0x8,
        'hook'     : 0x7D3774,
        'idx_off'  : 0x8,
        'n_slots'  : 0x10,
        'sig'      : [(-16, 0x0B080B00), (-12, 0xB9000AA8), (-8, 0x9424A30D), (-4, 0xB9400008), (0, 0x7100011F), (12, 0x340007A8)],
    },
    'add_hook'  : {
        'add_pc'   : 0x7D2910,
        'ctx_reg'  : 0x14,
        'displaced': 0xB9000015,
        'fn_val_reg': 0x15,
        'hook'     : 0x7D291C,
        'idx_off'  : 0x0,
        'sig'      : [(-20, 0xB9400288), (-12, 0x0B080A60), (-4, 0x9424A6A2), (0, 0xB9000015)],
    },
    'fields'    : {
        'field_6'   : (0x06, 16, 's'),
        'field_8'   : (0x08, 16, 's'),
        'field_E'   : (0x0E, 16, 's'),
        'n_frames'  : (0x04, 16, 'u'),
    },
    'cases'     : [
        ('battle_camera_position_sub_5C5B9C', 0x5C5B9C, [('n_frames', 'mul')], None),
        ('battle_camera_focal_sub_5C5F5E', 0x5C5F5E, [('n_frames', 'mul')], None),
        ('battle_camera_position_sub_5C557D', 0x5C557D, [('n_frames', 'mul')], None),
        ('battle_camera_focal_sub_5C5714', 0x5C5714, [('n_frames', 'mul')], None),
        ('battle_camera_position_sub_5C3D0D', 0x5C3D0D, [('n_frames', 'mul'), ('field_8', 'div'), ('field_6', 'div'), ('field_E', 'div')], None),
    ],
  },
  'effect60': {
    'what'      : 'per-frame battle effects -- auras, smoke, damage display, Vincent limit camera',
    'slots'     : 0x3C,
    'stride'    : 0x20,
    'mask_bits' : 0x6,
    'flag'      : None,
    'unhandled' : 0x0,
    'data_base' : 0xBFC3A0,
    'array_fn'  : 0xBFB1B0,
    'disp_x86'  : 0x5BF1C2,
    'disp_arm'  : 0x7D3470,
    'add_x86'   : 0x5BED92,
    'add_arm'   : 0x7C94E0,
    'throttle'  : {
        'pre'           : 0x7D3560,
        'pre_displaced' : 0xB90012A8,
        'post'          : 0x7D3568,
        'post_displaced': 0x2A1303E0,
        'call_pc'       : 0x7D3564,
        'translate_pc'  : 0x7D3550,
        'thunk'         : 0xA1A0,
        'ctx_reg'       : 0x15,
        'store_reg'     : 0x8,
        'ctr'           : 0x3FEC458,
        'pptr'          : 0x3FEC498,
        'saved'         : 0x3FEC4A0,
        'did'           : 0x3FEC4A1,
        'mask_bits'     : 0x6,
        'size'          : 0x50,
        'one_call_throttled': True,
        'pre_sig'       : [(-16, 0x9424A394), (-12, 0xB94012A8), (-8, 0xB9400000), (-4, 0x51001108), (0, 0xB90012A8), (4, 0x97E0DB0F), (8, 0x2A1303E0)],
        'post_sig'      : [(-24, 0x9424A394), (-20, 0xB94012A8), (-16, 0xB9400000), (-12, 0x51001108), (-8, 0xB90012A8), (-4, 0x97E0DB0F), (0, 0x2A1303E0)],
        'undecorated'   : [],
        'undecorated_words': [],
        'exclude'       : [
            ('battle_sub_4276B6', 0x4276B6),
            ('battle_sub_4255B7', 0x4255B7),
            ('battle_sub_427737', 0x427737),
            ('battle_sub_425AAD', 0x425AAD),
            ('battle_sub_427AF1', 0x427AF1),
            ('battle_sub_4277B1', 0x4277B1),
            ('battle_sub_5BD96D', 0x5BD96D),
            ('battle_sub_425E5F', 0x425E5F),
            ('battle_sub_5C1C8F', 0x5C1C8F),
            ('battle_sub_5BCF9D', 0x5BCF9D),
            ('handle_aura_effects_425520', 0x425520),
            ('battle_boss_death_sub_5BC5EC', 0x5BC5EC),
            ('battle_sub_5BCD42', 0x5BCD42),
            ('display_battle_damage_5BB410', 0x5BB410),
            ('limit_break_aura_effects_5C0572', 0x5C0572),
            ('enemy_skill_aura_effects_5C06BF', 0x5C06BF),
            ('summon_aura_effects_5C0953', 0x5C0953),
            ('battle_sub_5C18BC', 0x5C18BC),
        ],
        'candidates'    : [
            ('vincent_limit_satan_slam_camera_45CF2A', 0x45CF2A),
            ('battle_smoke_move_handler_5BE4E2', 0x5BE4E2),
        ],
        'aura_allow'    : [
            ('aura_spawner_5C0AFF', 0x5C0AFF),
            ('magic_aura_effects_5C0300', 0x5C0300),
        ],
    },
    'disp_hook' : {
        'add_pc'   : 0x7D351C,
        'ctx_reg'  : 0x15,
        'displaced': 0x7100011F,
        'fn_reg'   : 0x8,
        'hook'     : 0x7D352C,
        'idx_off'  : 0x8,
        'n_slots'  : 0x3C,
        'sig'      : [(-16, 0x0B080B00), (-12, 0xB9000AA8), (-8, 0x9424A39F), (-4, 0xB9400008), (0, 0x7100011F), (12, 0x34000728)],
    },
    'add_hook'  : {
        'add_pc'   : 0x7C976C,
        'ctx_reg'  : 0x14,
        'displaced': 0xB9000016,
        'fn_val_reg': 0x16,
        'hook'     : 0x7C9778,
        'idx_off'  : 0x8,
        'sig'      : [(-20, 0xB9400A88), (-12, 0x0B080AA0), (-4, 0x9424CB0B), (0, 0xB9000016)],
    },
    'fields'    : {
        'field_14'  : (0x14, 32, 's'),
        'field_18'  : (0x18, 8, 'u'),
        'field_19'  : (0x19, 8, 'u'),
        'field_1A'  : (0x1A, 16, 's'),
        'field_2'   : (0x02, 16, 's'),
        'field_6'   : (0x06, 16, 's'),
        'field_A'   : (0x0A, 16, 's'),
        'field_C'   : (0x0C, 16, 's'),
        'field_E'   : (0x0E, 16, 's'),
        'n_frames'  : (0x04, 16, 's'),
    },
    'cases'     : [
    ],
  },
}

# Opcode 0xF5 -- "wait N frames" -- in the two battle camera
# script interpreters. This is what paces the magic, limit
# break, summon and enemy-attack cameras; they are script
# driven, not slot-function driven, which is why neither
# camera-scale nor the pause-throttle could reach them.
CAMERA_WAIT_SITES = {
  'camera-position': {
    'what'            : 'camera POSITION script waits -- magic, limit break, summon, enemy attack, battle intro',
    'fn_x86'          : 0x5C23D1,
    'fn_arm'          : 0x7E6300,
    'array'           : 0xBE10F0,
    'current_position': 0xBE10F8,
    'frames_to_wait'  : 0xBE10FA,
    'hook'            : 0x7E7814,
    'displaced'       : 0x79000013,
    'val_reg'         : 0x13,
    'ctx_reg'         : 0x1A,
    'operand_pc'      : 0x7E77E4,
    'sig'             : [(-48, 0x39C00008), (-44, 0x79000348), (-24, 0x1B1C7D08), (-20, 0x79400353), (-16, 0x0B1B0109), (-12, 0x11000920), (-8, 0xB9000748), (-4, 0x942452E4), (0, 0x79000013)],
  },
  'camera-focal': {
    'what'            : 'camera FOCAL POINT script waits -- the same scripts, aiming rather than placing',
    'fn_x86'          : 0x5C3FD5,
    'fn_arm'          : 0x7E2580,
    'array'           : 0xBE1130,
    'current_position': 0xBE1138,
    'frames_to_wait'  : 0xBE113A,
    'hook'            : 0x7E3750,
    'displaced'       : 0x79000013,
    'val_reg'         : 0x13,
    'ctx_reg'         : 0x1A,
    'operand_pc'      : 0x7E3720,
    'sig'             : [(-48, 0x39C00008), (-44, 0x79000348), (-24, 0x1B1C7D08), (-20, 0x79400353), (-16, 0x0B1B0109), (-12, 0x11000920), (-8, 0xB9000748), (-4, 0x94246315), (0, 0x79000013)],
  },
}

# Field script opcode 0x24 (WAIT). The field opcode table is at guest
# 0x9055A0; entry 0x24 is the handler at x86 0x610818 (cross-checked the
# same way FFNx does it: entry 0x21 is opcode_tutor and entry 0x25 is
# NFADE = 0x61E099, which is the handler the NFADE opcode scaler already
# resolves independently).
#
# Inside the handler the operand is assembled from two script bytes and
# written to wait_frames[entity] (guest 0xCC0900) exactly once, at
# +0xA1:  mov word ptr [ecx*2 + 0xCC0900], ax
#
# In the ARM64 translation that is `strh w20, [x0]` at module +0x951D00.
# Three other `strh` in this function also target wait_frames -- the low
# byte at x86 +0x5D, the zeroing at +0xFB and the decrement at +0x149 --
# so the signature below is not decoration: it is the only thing that
# distinguishes the store that carries the finished 16-bit value.
FIELD_WAIT_SITES = {
  'field-wait': {
    'what'            : 'field script opcode 0x24 (WAIT) frame counts -- scripted set pieces, alarms, timed NPC business',
    'fn_x86'          : 0x610818,
    'fn_arm'          : 0x951A80,
    'opcode_table'    : 0x9055A0,
    'opcode_index'    : 0x24,
    'wait_frames'     : 0xCC0900,
    'x86_store'       : 0x6108B9,          # handler + 0xA1
    'hook'            : 0x951D00,
    'displaced'       : 0x79000014,        # strh w20, [x0]
    'val_reg'         : 0x14,
    'sig'             : [(-40, 0x2A1303E0), (-36, 0x790002A8), (-32, 0xB90006BF), (-28, 0x941EA9AF), (-24, 0x39400008), (-20, 0x390012A8), (-16, 0xB94006A8), (-12, 0x794002B4), (-8, 0x0B080700), (-4, 0x941EA9A9), (0, 0x79000014)],
  },
}

# Field model eye-blink SHUT DURATION, in field_animate_3d_models_6392BB.
#
# The state machine writes "eyes shut" and reloads the interval counter in the
# SAME arm, so mode 2 can only ever last one frame:
#
#     if (counter == 0) { mode = 2; counter = reload; }   <- one frame, always
#     else              { mode = 1; counter--;        }
#
# At 30 FPS that is 33 ms and reads as a blink. At 60 FPS it is 16 ms and
# reads as a flicker. Making it two frames means the reload has to become
# conditional, which is why the `field-blink` constants alone could not do it.
#
# Two caves, no new state -- the counter carries the state itself. The test is
# widened to `counter <= 0` (it is loaded with `ldrsh`, so it is already
# signed), and the reload stores -1 the first time through and the real value
# the second:
#
#     counter 1 -> mode 1, counter 0
#     counter 0 -> mode 2, cave stores -1        <- shut, frame 1
#     counter -1 -> mode 2, cave stores reload   <- shut, frame 2
#     counter reload -> mode 1
#
# Cycle length becomes reload + 2 = 130..193 frames at 60 FPS = 2.17..3.22 s,
# against vanilla's 64..95 + 1 = 65..96 frames at 30 FPS = 2.17..3.20 s. So
# the interval constants in `field-blink` stay exactly as they are and the two
# groups compose.
FIELD_BLINK_SITES = {
  'test': {
    'what'        : 'blink test: counter == 0 -> counter <= 0',
    'fn_x86'      : 0x6392BB,
    'fn_arm'      : 0x949B60,
    'counter'     : 0xCC167A,
    'hook'        : 0x094B5B8,
    'displaced'   : 0x34000514,        # cbz w20, #0x94b658
    'val_reg'     : 0x14,              # w20 = counter, sign-extended
    'blink_arm'   : 0x0094B658,        # the "eyes shut" arm
    'sig'         : [(-24, 0x11264260), (-20, 0x7100029F), (-16, 0x1A9F17E8), (-12, 0xB9000AB4), (-8, 0x39008EA8), (-4, 0x941EC37B), (0, 0x34000514), (4, 0x3900001A)],
  },
  'hold': {
    'what'        : 'blink reload: hold shut one more frame before reloading',
    'fn_x86'      : 0x6392BB,
    'fn_arm'      : 0x949B60,
    'counter'     : 0xCC167A,
    'hook'        : 0x094B704,
    'displaced'   : 0x7900001B,        # strh w27, [x0]
    'val_reg'     : 0x1B,              # w27 = the freshly computed reload
    'sig'         : [(-24, 0x0B081108), (-20, 0x794002BB), (-16, 0x531D7108), (-12, 0x0B160100), (-8, 0xB90006A8), (-4, 0x941EC328), (0, 0x7900001B), (4, 0x2A1403E0)],
  },
}
