# GENERATED by ff7nx_wsdata.emit_exception_table -- do not edit.
# source: cache/CosmosLimitBreak/CONFIG/widescreen/config.toml
#
# is_fieldmap_wide() is binary, so the module needs one bit per
# field. This names the minority and defaults to the majority:
#     641 wide, 61 not wide, 1 zoom
# Names are SECTION 8 names (<=9 bytes), not archive entry names.

WIDE_BY_DEFAULT = True
NAME_LEN = 9
# the listed names are the EXCEPTIONS to WIDE_BY_DEFAULT
EXCEPTIONS = [
    'blinele',
    'blinst_1',
    'blinst_2',
    'blinst_3',
    'bugin1a',
    'colne_b3',
    'convil_2',
    'corelin',
    'cosin4',
    'cosin5',
    'cosmin6',
    'elmtow',
    'ghotin_2',
    'ghotin_3',
    'gldelev',
    'gldinfo',
    'gninn',
    'gomin',
    'gon_i',
    'gon_wa1',
    'gon_wa2',
    'hideway1',
    'hideway2',
    'hideway3',
    'hyoumap',
    'jailin1',
    'jailin2',
    'jailin3',
    'jailin4',
    'junbin12',
    'junele1',
    'junin1a',
    'kuro_2',
    'md8_4',
    'mds5_dk',
    'mkt_ia',
    'mkt_m',
    'mkt_s1',
    'mkt_s2',
    'mkt_s3',
    'mkt_w',
    'mtcrl_7',
    'ncoin1',
    'ncoin2',
    'ncoin3',
    'ncoinn',
    'nivl_e3',
    'nvdun2',
    'nvmin1_2',
    'sbwy4_1',
    'semkin_1',
    'tower5',
    'tunnel_5',
    'uta_im',
    'uta_wa',
    'utmin1',
    'utmin2',
    'uttmpin4',
    'white2',
    'yufy1',
    'zz1',
]

ZOOM = ['ztruck']

# 549 bytes, 61 entries x 9
BLOB = (
    b'blinele\x00\x00bli'
    b'nst_1\x00blinst'
    b'_2\x00blinst_3\x00'
    b'bugin1a\x00\x00col'
    b'ne_b3\x00convil'
    b'_2\x00corelin\x00\x00'
    b'cosin4\x00\x00\x00cos'
    b'in5\x00\x00\x00cosmin'
    b'6\x00\x00elmtow\x00\x00\x00'
    b'ghotin_2\x00gho'
    b'tin_3\x00gldele'
    b'v\x00\x00gldinfo\x00\x00'
    b'gninn\x00\x00\x00\x00gom'
    b'in\x00\x00\x00\x00gon_i\x00'
    b'\x00\x00\x00gon_wa1\x00\x00'
    b'gon_wa2\x00\x00hid'
    b'eway1\x00hidewa'
    b'y2\x00hideway3\x00'
    b'hyoumap\x00\x00jai'
    b'lin1\x00\x00jailin'
    b'2\x00\x00jailin3\x00\x00'
    b'jailin4\x00\x00jun'
    b'bin12\x00junele'
    b'1\x00\x00junin1a\x00\x00'
    b'kuro_2\x00\x00\x00md8'
    b'_4\x00\x00\x00\x00mds5_d'
    b'k\x00\x00mkt_ia\x00\x00\x00'
    b'mkt_m\x00\x00\x00\x00mkt'
    b'_s1\x00\x00\x00mkt_s2'
    b'\x00\x00\x00mkt_s3\x00\x00\x00'
    b'mkt_w\x00\x00\x00\x00mtc'
    b'rl_7\x00\x00ncoin1'
    b'\x00\x00\x00ncoin2\x00\x00\x00'
    b'ncoin3\x00\x00\x00nco'
    b'inn\x00\x00\x00nivl_e'
    b'3\x00\x00nvdun2\x00\x00\x00'
    b'nvmin1_2\x00sbw'
    b'y4_1\x00\x00semkin'
    b'_1\x00tower5\x00\x00\x00'
    b'tunnel_5\x00uta'
    b'_im\x00\x00\x00uta_wa'
    b'\x00\x00\x00utmin1\x00\x00\x00'
    b'utmin2\x00\x00\x00utt'
    b'mpin4\x00white2'
    b'\x00\x00\x00yufy1\x00\x00\x00\x00'
    b'zz1\x00\x00\x00\x00\x00\x00'
)
